[package]
name = "aom-sys"
version = "0.1.4"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to aom"
repository = "https://github.com/rust-av/aom-rs"
edition = "2018"
build = "build.rs"

[package.metadata.pkg-config]
aom = "0.1.0"

[features]
build_sources = []

[build-dependencies]
bindgen = "0.54"
metadeps = "1.1.2"

[dependencies]
