[package]
name = "aom-sys"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to aom"
repository = "https://github.com/rust-av/aom-rs"

build = "build.rs"

[package.metadata.pkg-config]
aom = "0.1.0"

[features]
build_sources = []

[build-dependencies]
bindgen = "0.47.2"
metadeps = "1.1.2"
pkg-config = "0.3.12"
cmake = "0.1.33"

[dependencies]
